In [4]:
import pandas as pd

files={
    'demo':'DEMO_J.xpt',
    'diabetes':'DIQ_J.xpt',
    'glocose':'GLU_J.xpt',
    'bmi':'BMX_J.xpt',
    'liver':'BIO_PRO_J.xpt',
    'target':'MCQ_J.xpt',
    'unknown':'TCHOL_J.xpt'
}

In [5]:
import pandas as pd

df_demo = pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\DEMO_J.xpt")

df_demo.sample(10){{
df_demo.shape

SyntaxError: '{' was never closed (470826405.py, line 5)

In [6]:
df_demo.describe()

NameError: name 'df_demo' is not defined

In [7]:
df_diabetes = pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\DIQ_J.xpt")
df_diabetes[['SEQN','DIQ010']]

          SEQN  DIQ010
0      93703.0     2.0
1      93704.0     2.0
2      93705.0     2.0
3      93706.0     2.0
4      93707.0     2.0
...        ...     ...
8892  102952.0     3.0
8893  102953.0     2.0
8894  102954.0     2.0
8895  102955.0     2.0
8896  102956.0     2.0

[8897 rows x 2 columns]

In [8]:
df_glucose = pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\GLU_J.xpt")
df_glucose.head()

      SEQN      WTSAF2YR  LBXGLU  LBDGLUSI
0  93708.0  2.565368e+04   122.0      6.77
1  93711.0  2.922605e+04   107.0      5.94
2  93717.0  1.371510e+05    91.0      5.05
3  93718.0  5.888331e+04    89.0      4.94
4  93719.0  5.397605e-79    86.0      4.77

In [9]:
df_bmx = pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\BMX_J.xpt")
df_bmx.sample(10)

,SEQN,BMDSTATS,BMXWT,BMIWT,BMXRECUM,BMIRECUM,BMXHEAD,BMIHEAD,BMXHT,BMIHT,...,BMXLEG,BMILEG,BMXARML,BMIARML,BMXARMC,BMIARMC,BMXWAIST,BMIWAIST,BMXHIP,BMIHIP
5069,99064.0,1.0,89.0,NaN,NaN,NaN,NaN,NaN,162.2,NaN,...,34.0,NaN,37.5,NaN,30.5,NaN,124.6,NaN,114.7,NaN
3588,97495.0,1.0,168.9,NaN,NaN,NaN,NaN,NaN,162.2,NaN,...,34.0,NaN,40.4,NaN,46.0,NaN,164.9,NaN,173.3,NaN
3547,97454.0,1.0,39.4,NaN,NaN,NaN,NaN,NaN,132.1,NaN,...,34.0,NaN,28.0,NaN,24.7,NaN,68.5,NaN,NaN,NaN
1060,94825.0,1.0,24.1,NaN,NaN,NaN,NaN,NaN,124.3,NaN,...,NaN,NaN,26.3,NaN,17.9,NaN,54.9,NaN,NaN,NaN
5658,99691.0,1.0,64.9,NaN,NaN,NaN,NaN,NaN,166.0,NaN,...,36.0,NaN,38.5,NaN,26.7,NaN,80.4,NaN,100.2,NaN
6038,100102.0,1.0,95.5,NaN,NaN,NaN,NaN,NaN,171.3,NaN,...,40.4,NaN,39.0,NaN,39.6,NaN,110.7,NaN,104.0,NaN
2170,95995.0,2.0,63.3,3.0,NaN,NaN,NaN,NaN,147.8,NaN,...,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0,NaN,1.0
2445,96291.0,3.0,136.5,NaN,NaN,NaN,NaN,NaN,165.6,NaN,...,NaN,1.0,39.0,NaN,47.2,NaN,126.2,NaN,155.3,NaN
1756,95566.0,1.0,110.4,NaN,NaN,NaN,NaN,NaN,166.8,NaN,...,39.7,NaN,37.4,NaN,37.6,NaN,125.8,NaN,141.7,NaN
8217,102434.0,1.0,111.1,NaN,NaN,NaN,NaN,NaN,165.3,NaN,...,37.5,NaN,37.0,NaN,39.2,NaN,123.8,NaN,129.7,NaN

In [10]:
df_liver_heart= pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\BIOPRO_J.xpt")
df_liver_heart['LBXSAT']

KeyError: 'LBXSAT'

In [ ]:
df_res = pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\MCQ_J.xpt")
df_res.shape

In [11]:
df_temp= pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\TCHOL_J.xpt")
df_temp.sample(10)

          SEQN  LBXTC  LBDTCSI
4748   99589.0    NaN      NaN
6726  102081.0  225.0     5.82
1914   96068.0  130.0     3.36
2057   96247.0  120.0     3.10
6025  101209.0    NaN      NaN
4590   99404.0  195.0     5.04
793    94679.0  249.0     6.44
5757  100882.0  173.0     4.47
4901   99785.0  169.0     4.37
6528  101822.0  180.0     4.65

In [12]:
df_vitals= pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\BIOPRO_J.xpt")
df_labels=pd.read_sas(r"C:\Users\Dev Patel\Desktop\jupyter projects\Health_risk_predictor\DIQ_J.xpt")

df_vitals = df_vitals[['SEQN', 'LBXSGL', 'LBXSIR']]
df_labels = df_labels[['SEQN', 'DIQ010']] 

df_combined = pd.merge(df_vitals, df_labels, on='SEQN', how='inner')

print(f"Combined data shape: {df_combined.shape}")

Combined data shape: (6401, 4)

In [13]:
# Calculate correlation specifically between feature and target
correlation = df_combined[['LBXSGL','LBXSIR']].corrwith(df_combined['DIQ010'])
print(f"Correlation: {correlation}")

Correlation: LBXSGL   -0.380646
LBXSIR    0.049435
dtype: float64

In [14]:
import pandas as pd
import numpy as np

# 1. Define your "Ingredients" (Files and the specific columns we want)
# This prevents 'Feature Bloat'
file_map = {
    'DEMO_J.XPT': ['SEQN', 'RIAGENDR', 'RIDAGEYR'],           # Demographics
    'BMX_J.XPT':  ['SEQN', 'BMXBMI', 'BMXWAIST'],             # Body Measures
    'BIOPRO_J.XPT': ['SEQN', 'LBXSGL', 'LBXSIR', 'LBDSATLC'],    # Lab: Glucose, Bilirubin, ALT
    'DIQ_J.XPT':  ['SEQN', 'DIQ010'],                         # Target: Diabetes
    'MCQ_J.XPT':  ['SEQN', 'MCQ160C', 'MCQ160L']               # Targets: Heart, Liver
}

# 2. Load and Merge
df_final = None

for file, cols in file_map.items():
    df_temp = pd.read_sas(file)[cols]
    if df_final is None:
        df_final = df_temp
    else:
        # Use an 'inner' join if you only want people who did EVERYTHING
        # Use 'left' if you want to keep everyone and handle missing values later
        df_final = pd.merge(df_final, df_temp, on='SEQN', how='left')

print(f"Master Dataset Shape: {df_final.shape}")

Master Dataset Shape: (9254, 11)

In [15]:
from sklearn.feature_selection import mutual_info_classif

targets = ['DIQ010', 'MCQ160C', 'MCQ160L'] # Diabetes, Heart, Liver
features = ['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC']

for t in targets:
    temp_df=df_final.dropna(subset=[t]+features)
    mi_scores=mutual_info_classif(temp_df[features],temp_df[t])

    print(f"\n--- Feature Importance for {t} ---")
    for score, feat in sorted(zip(mi_scores, features), reverse=True):
        print(f"{feat}: {score:.4f}")

--- Feature Importance for DIQ010 ---
LBXSGL: 0.1514
RIDAGEYR: 0.0701
BMXBMI: 0.0161
LBXSIR: 0.0050
RIAGENDR: 0.0035
LBDSATLC: 0.0011

--- Feature Importance for MCQ160C ---
RIDAGEYR: 0.0299
RIAGENDR: 0.0105
LBXSGL: 0.0048
LBDSATLC: 0.0015
LBXSIR: 0.0007
BMXBMI: 0.0004

--- Feature Importance for MCQ160L ---
LBXSGL: 0.0106
RIDAGEYR: 0.0058
RIAGENDR: 0.0038
LBDSATLC: 0.0035
BMXBMI: 0.0023
LBXSIR: 0.0012

In [16]:
# The "What's actually in there?" check
print(df_final['DIQ010'].value_counts(dropna=False))

DIQ010
2.0    7816
1.0     893
NaN     357
3.0     184
9.0       4
Name: count, dtype: int64

In [17]:
df_final['DIQ010'] = df_final['DIQ010'].replace({1.0: 1, 2.0: 0, 7.0: np.nan, 9.0: np.nan,3.0:np.nan})

In [18]:
print(df_final['DIQ010'].value_counts(dropna=False))

DIQ010
0.0    7816
1.0     893
NaN     545
Name: count, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

# 1. Drop the NaNs to get our "Ground Truth" rows
df_diabetes_ready = df_final.dropna(subset=['DIQ010'])

df_clean = df_diabetes_ready.dropna(subset=['RIDAGEYR','BMXBMI','LBXSGL'])
# 2. Define Features (X) and Target (y)
# Let's start with a few key features for now
X = df_clean[['RIDAGEYR', 'BMXBMI', 'LBXSGL']] 
y = df_clean['DIQ010']

# 3. The Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

diabetes_model=Pipeline([
    ('scalar',StandardScaler()),
    ('classifier',LogisticRegression(class_weight='balanced'))
])

diabetes_model.fit(X_train,y_train)

Pipeline(steps=[('scalar', StandardScaler()),
                ('classifier', LogisticRegression(class_weight='balanced'))])

In [21]:
from sklearn.metrics import classification_report, roc_auc_score

y_pred = diabetes_model.predict(X_test)
print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, diabetes_model.predict_proba(X_test)[:, 1])}")

              precision    recall  f1-score   support

         0.0       0.97      0.81      0.88       973
         1.0       0.41      0.82      0.55       156

    accuracy                           0.81      1129
   macro avg       0.69      0.82      0.72      1129
weighted avg       0.89      0.81      0.84      1129

ROC-AUC Score: 0.9064616438717158

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# 1. Create the "Forest" Pipeline
# n_estimators=100 means we are building 100 individual trees
diabetes_rf_model = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', RandomForestClassifier(
        n_estimators=100, 
        class_weight='balanced', 
        random_state=42,
        max_depth=5 # We limit depth to prevent "Memorization" (Overfitting)
    ))
])

# 2. Train
diabetes_rf_model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=5,
                                        random_state=42))])

In [23]:
# Extract the importance from the trained model
importances = diabetes_rf_model.named_steps['classifier'].feature_importances_
feature_names = X.columns

# Sort and Plot
for score, name in sorted(zip(importances, feature_names), reverse=True):
    print(f"{name}: {score:.4f}")

LBXSGL: 0.5371
RIDAGEYR: 0.3446
BMXBMI: 0.1183

In [24]:
df_final.sample(10)

,SEQN,RIAGENDR,RIDAGEYR,BMXBMI,BMXWAIST,LBXSGL,LBXSIR,LBDSATLC,DIQ010,MCQ160C,MCQ160L
8806,102509.0,1.0,62.0,19.5,81.4,626.0,84.0,5.397605e-79,0.0,2.0,2.0
3216,96919.0,2.0,12.0,17.0,60.0,106.0,79.0,5.397605e-79,0.0,NaN,NaN
7302,101005.0,2.0,29.0,21.6,NaN,93.0,56.0,5.397605e-79,0.0,2.0,2.0
5137,98840.0,2.0,50.0,35.1,103.5,93.0,90.0,5.397605e-79,0.0,2.0,2.0
443,94146.0,2.0,2.0,18.2,49.7,NaN,NaN,NaN,0.0,NaN,NaN
301,94004.0,2.0,25.0,30.1,101.6,87.0,31.0,5.397605e-79,0.0,2.0,2.0
3997,97700.0,2.0,5.0,16.4,51.1,NaN,NaN,NaN,0.0,NaN,NaN
560,94263.0,1.0,17.0,19.5,72.4,84.0,79.0,5.397605e-79,0.0,NaN,NaN
7169,100872.0,2.0,71.0,29.8,110.7,118.0,97.0,5.397605e-79,1.0,2.0,2.0
4375,98078.0,2.0,9.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN

In [25]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9254 entries, 0 to 9253
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      9254 non-null   float64
 1   RIAGENDR  9254 non-null   float64
 2   RIDAGEYR  9254 non-null   float64
 3   BMXBMI    8005 non-null   float64
 4   BMXWAIST  7601 non-null   float64
 5   LBXSGL    5901 non-null   float64
 6   LBXSIR    5902 non-null   float64
 7   LBDSATLC  5902 non-null   float64
 8   DIQ010    8709 non-null   float64
 9   MCQ160C   5569 non-null   float64
 10  MCQ160L   5569 non-null   float64
dtypes: float64(11)
memory usage: 795.4 KB

In [26]:
import numpy as np

# Mapping: 1 is Yes (Sick), 2 is No (Healthy). Everything else is noise.
target_map = {1.0: 1, 2.0: 0, 7.0: np.nan, 9.0: np.nan}

df_final['MCQ160C'] = df_final['MCQ160C'].replace(target_map) # Heart
df_final['MCQ160L'] = df_final['MCQ160L'].replace(target_map) # Liver

In [27]:
from sklearn.model_selection import train_test_split

# These are the columns your app will eventually ask the user for
features = ['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC']

def prepare_split(df, target_col, feature_cols):
    # 1. Drop rows where THIS specific target is missing
    df_clean = df_final.dropna(subset=[target_col] + feature_cols)
    
    X = df_clean[feature_cols]
    y = df_clean[target_col]
    
    # 2. Split into 80% Training and 20% Testing
    # Stratify=y keeps the 9:1 ratio consistent in both sets
    return train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Execute the splits for each 'Specialist'
X_train_dia, X_test_dia, y_train_dia, y_test_dia = prepare_split(df_final, 'DIQ010', features)
X_train_hrt, X_test_hrt, y_train_hrt, y_test_hrt = prepare_split(df_final, 'MCQ160C', features)
X_train_lvr, X_test_lvr, y_train_lvr, y_test_lvr = prepare_split(df_final, 'MCQ160L', features)

print(f"Diabetes Training Samples: {len(X_train_dia)}")
print(f"Heart Training Samples: {len(X_train_hrt)}")
print(f"Liver Training Samples: {len(X_train_lvr)}")

Diabetes Training Samples: 4512
Heart Training Samples: 3856
Liver Training Samples: 3857

In [30]:
pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from optuna) (2.2.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from optuna) (25.0)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: tqdm in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from alembic>=1.5.0->optuna) (4.13.2)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.3.2-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: colorama in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\dev patel\appdata\local\programs\python\python313\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.2 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.0 MB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 1.1 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 1.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.3 MB/s  0:00:01
Downloading greenlet-3.3.2-cp313-cp313-win_amd64.whl (230 kB)
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: Mako, greenlet, colorlog, sqlalchemy, alembic, optuna

   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ---------------------------------------- 0/6 [Mako]
   ------ --------------------------------- 1/6 [greenlet]
   ------ --------------------------------- 1/6 [greenlet]
   ------ --------------------------------- 1/6 [greenlet]
   ------ --------------------------------- 1/6 [greenlet]
   ------ --------------------------------- 1/6 [greenlet]
   ------------- -------------------------- 2/6 [colorlog]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------- ------------------- 3/6 [sqlalchemy]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   -------------------------- ------------- 4/6 [alembic]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   --------------------------------- ------ 5/6 [optuna]
   ---------------------------------------- 6/6 [optuna]

Successfully installed Mako-1.3.10 alembic-1.18.4 colorlog-6.10.1 greenlet-3.3.2 optuna-4.8.0 sqlalchemy-2.0.48
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
best_params1=study.best_params

In [61]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train,y_train):
    param={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'eval_metric': 'logloss'
    }

    model1=XGBClassifier(**param)
    model1.fit(X_train,y_train)

    preds=model1.predict_proba(X_test_dia)[:,1]
    return roc_auc_score(y_test_dia,preds)

study1=optuna.create_study(direction='maximize')
study1.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)

print(f"Best Parameters: {study1.best_params}")

[I 2026-04-03 20:25:20,885] A new study created in memory with name: no-name-4c95255b-2cc1-4585-8e0b-72351aced2ef
[I 2026-04-03 20:25:21,239] Trial 0 finished with value: 0.9079152157855862 and parameters: {'n_estimators': 112, 'max_depth': 7, 'learning_rate': 0.04381281539701872}. Best is trial 0 with value: 0.9079152157855862.
[I 2026-04-03 20:25:21,738] Trial 1 finished with value: 0.9085878970138229 and parameters: {'n_estimators': 235, 'max_depth': 5, 'learning_rate': 0.19646898841660923}. Best is trial 1 with value: 0.9085878970138229.
[I 2026-04-03 20:25:21,940] Trial 2 finished with value: 0.913329640181492 and parameters: {'n_estimators': 90, 'max_depth': 5, 'learning_rate': 0.1666732525205636}. Best is trial 2 with value: 0.913329640181492.
[I 2026-04-03 20:25:22,117] Trial 3 finished with value: 0.9093001477260736 and parameters: {'n_estimators': 55, 'max_depth': 7, 'learning_rate': 0.25412662281889026}. Best is trial 2 with value: 0.913329640181492.
[I 2026-04-03 20:25:22,372] Trial 4 finished with value: 0.9123008335971299 and parameters: {'n_estimators': 96, 'max_depth': 6, 'learning_rate': 0.06161232469654183}. Best is trial 2 with value: 0.913329640181492.
[I 2026-04-03 20:25:23,362] Trial 5 finished with value: 0.9082119869156906 and parameters: {'n_estimators': 237, 'max_depth': 10, 'learning_rate': 0.12380399672361474}. Best is trial 2 with value: 0.913329640181492.
[I 2026-04-03 20:25:23,959] Trial 6 finished with value: 0.9016632373113853 and parameters: {'n_estimators': 287, 'max_depth': 5, 'learning_rate': 0.27753111648868367}. Best is trial 2 with value: 0.913329640181492.
[I 2026-04-03 20:25:24,110] Trial 7 finished with value: 0.9235847314551018 and parameters: {'n_estimators': 96, 'max_depth': 3, 'learning_rate': 0.2737785074202229}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:24,473] Trial 8 finished with value: 0.9151300517041258 and parameters: {'n_estimators': 173, 'max_depth': 5, 'learning_rate': 0.07984350872442628}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:24,659] Trial 9 finished with value: 0.9197728711617601 and parameters: {'n_estimators': 98, 'max_depth': 4, 'learning_rate': 0.1404836618796575}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:24,901] Trial 10 finished with value: 0.921744750448454 and parameters: {'n_estimators': 157, 'max_depth': 3, 'learning_rate': 0.2234517623771533}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:25,149] Trial 11 finished with value: 0.9203400337659596 and parameters: {'n_estimators': 159, 'max_depth': 3, 'learning_rate': 0.22262696050786565}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:25,359] Trial 12 finished with value: 0.9200564524638599 and parameters: {'n_estimators': 137, 'max_depth': 3, 'learning_rate': 0.2888732376212591}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:25,677] Trial 13 finished with value: 0.9145496992719215 and parameters: {'n_estimators': 214, 'max_depth': 3, 'learning_rate': 0.24402875915757627}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:25,930] Trial 14 finished with value: 0.9066951566951568 and parameters: {'n_estimators': 52, 'max_depth': 10, 'learning_rate': 0.19115752166539812}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:26,421] Trial 15 finished with value: 0.9104740424184867 and parameters: {'n_estimators': 138, 'max_depth': 8, 'learning_rate': 0.2280368510417073}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:26,786] Trial 16 finished with value: 0.9102827899124195 and parameters: {'n_estimators': 194, 'max_depth': 4, 'learning_rate': 0.29563110263580294}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:27,041] Trial 17 finished with value: 0.9132109317294501 and parameters: {'n_estimators': 132, 'max_depth': 4, 'learning_rate': 0.19182161657604518}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:27,339] Trial 18 finished with value: 0.9070446871372797 and parameters: {'n_estimators': 81, 'max_depth': 8, 'learning_rate': 0.2639704704929819}. Best is trial 7 with value: 0.9235847314551018.
[I 2026-04-03 20:25:27,583] Trial 19 finished with value: 0.9271756621293659 and parameters: {'n_estimators': 160, 'max_depth': 3, 'learning_rate': 0.10005131057858568}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:28,365] Trial 20 finished with value: 0.910642212725546 and parameters: {'n_estimators': 296, 'max_depth': 6, 'learning_rate': 0.010978566189445788}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:28,653] Trial 21 finished with value: 0.9256489395378285 and parameters: {'n_estimators': 190, 'max_depth': 3, 'learning_rate': 0.11865776069184755}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:29,012] Trial 22 finished with value: 0.9197530864197532 and parameters: {'n_estimators': 194, 'max_depth': 4, 'learning_rate': 0.10428305235567746}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:29,386] Trial 23 finished with value: 0.924468449931413 and parameters: {'n_estimators': 253, 'max_depth': 3, 'learning_rate': 0.09979016121054866}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:29,842] Trial 24 finished with value: 0.9173657275509127 and parameters: {'n_estimators': 271, 'max_depth': 4, 'learning_rate': 0.09933443645299973}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:30,208] Trial 25 finished with value: 0.9214809538883613 and parameters: {'n_estimators': 249, 'max_depth': 3, 'learning_rate': 0.14670540047821143}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:30,596] Trial 26 finished with value: 0.9174052970349266 and parameters: {'n_estimators': 211, 'max_depth': 4, 'learning_rate': 0.11627306406705598}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:30,986] Trial 27 finished with value: 0.926892080827266 and parameters: {'n_estimators': 267, 'max_depth': 3, 'learning_rate': 0.080609395336473}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:31,404] Trial 28 finished with value: 0.9136264113115965 and parameters: {'n_estimators': 199, 'max_depth': 5, 'learning_rate': 0.0718522109308078}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:32,105] Trial 29 finished with value: 0.9061609686609687 and parameters: {'n_estimators': 174, 'max_depth': 9, 'learning_rate': 0.034130415493629496}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:32,435] Trial 30 finished with value: 0.9125943072702332 and parameters: {'n_estimators': 118, 'max_depth': 6, 'learning_rate': 0.047387154949401836}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:32,823] Trial 31 finished with value: 0.9246959744644929 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.08895339514627867}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:33,218] Trial 32 finished with value: 0.9252136752136753 and parameters: {'n_estimators': 271, 'max_depth': 3, 'learning_rate': 0.08629776305497543}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:33,718] Trial 33 finished with value: 0.9118853540149836 and parameters: {'n_estimators': 278, 'max_depth': 4, 'learning_rate': 0.12816671777889996}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:34,046] Trial 34 finished with value: 0.9206895642080827 and parameters: {'n_estimators': 224, 'max_depth': 3, 'learning_rate': 0.16402389896041028}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:34,487] Trial 35 finished with value: 0.9217447504484542 and parameters: {'n_estimators': 243, 'max_depth': 4, 'learning_rate': 0.05662221135261267}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:34,842] Trial 36 finished with value: 0.9201553761738948 and parameters: {'n_estimators': 153, 'max_depth': 5, 'learning_rate': 0.03057004703191947}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:35,520] Trial 37 finished with value: 0.9112984066687772 and parameters: {'n_estimators': 226, 'max_depth': 7, 'learning_rate': 0.07377463453376158}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:35,906] Trial 38 finished with value: 0.9236539780521262 and parameters: {'n_estimators': 259, 'max_depth': 3, 'learning_rate': 0.11269285121941168}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:36,442] Trial 39 finished with value: 0.9109752558826633 and parameters: {'n_estimators': 299, 'max_depth': 4, 'learning_rate': 0.13360956000668367}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:36,850] Trial 40 finished with value: 0.9176822834230242 and parameters: {'n_estimators': 181, 'max_depth': 5, 'learning_rate': 0.08684338784518372}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:37,238] Trial 41 finished with value: 0.9246465126094756 and parameters: {'n_estimators': 266, 'max_depth': 3, 'learning_rate': 0.0908038715737444}. Best is trial 19 with value: 0.9271756621293659.
[I 2026-04-03 20:25:37,646] Trial 42 finished with value: 0.9280165136646619 and parameters: {'n_estimators': 284, 'max_depth': 3, 'learning_rate': 0.05531501063470465}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:38,035] Trial 43 finished with value: 0.9277197425345574 and parameters: {'n_estimators': 278, 'max_depth': 3, 'learning_rate': 0.061862704209398905}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:38,449] Trial 44 finished with value: 0.927053656220323 and parameters: {'n_estimators': 284, 'max_depth': 3, 'learning_rate': 0.062220799716823115}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:38,942] Trial 45 finished with value: 0.9193046322675953 and parameters: {'n_estimators': 286, 'max_depth': 4, 'learning_rate': 0.0608995787528856}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:39,363] Trial 46 finished with value: 0.9280132162076606 and parameters: {'n_estimators': 286, 'max_depth': 3, 'learning_rate': 0.016718556470194254}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:39,994] Trial 47 finished with value: 0.9189880763954837 and parameters: {'n_estimators': 282, 'max_depth': 5, 'learning_rate': 0.014832437131031185}. Best is trial 42 with value: 0.9280165136646619.
[I 2026-04-03 20:25:40,423] Trial 48 finished with value: 0.9288606626569589 and parameters: {'n_estimators': 295, 'max_depth': 3, 'learning_rate': 0.03039074434823795}. Best is trial 48 with value: 0.9288606626569589.
[I 2026-04-03 20:25:40,953] Trial 49 finished with value: 0.9235088899440752 and parameters: {'n_estimators': 294, 'max_depth': 4, 'learning_rate': 0.02654332385813198}. Best is trial 48 with value: 0.9288606626569589.

Best Parameters: {'n_estimators': 295, 'max_depth': 3, 'learning_rate': 0.03039074434823795}

In [45]:
best_params2=study1.best_params

In [ ]:
Diabetes Model

In [60]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_dia,y_train_dia):
    param1_dia={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'eval_metric': 'logloss'
    }

    model1_dia=XGBClassifier(**param1_dia)
    model1_dia.fit(X_train_dia,y_train_dia)

    preds=model1_dia.predict_proba(X_test_dia)[:,1]
    return roc_auc_score(y_test_dia,preds)

study1_dia=optuna.create_study(direction='maximize')
study1_dia.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)

print(f"Best Parameters: {study1_dia.best_params}")

[I 2026-04-03 20:25:00,392] A new study created in memory with name: no-name-b6b6bc7c-e8f4-4a80-bdfe-eb77c7b98544
[I 2026-04-03 20:25:00,683] Trial 0 finished with value: 0.9231263849319404 and parameters: {'n_estimators': 122, 'max_depth': 4, 'learning_rate': 0.055440031677956816}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:00,840] Trial 1 finished with value: 0.9140287010657381 and parameters: {'n_estimators': 66, 'max_depth': 5, 'learning_rate': 0.2928988787844828}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:01,328] Trial 2 finished with value: 0.9068798142872216 and parameters: {'n_estimators': 278, 'max_depth': 4, 'learning_rate': 0.28992668533703564}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:01,610] Trial 3 finished with value: 0.9124525166191831 and parameters: {'n_estimators': 108, 'max_depth': 6, 'learning_rate': 0.1616936799429028}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:01,968] Trial 4 finished with value: 0.9038461538461539 and parameters: {'n_estimators': 140, 'max_depth': 6, 'learning_rate': 0.26653473976990283}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:02,543] Trial 5 finished with value: 0.9096167035981851 and parameters: {'n_estimators': 227, 'max_depth': 6, 'learning_rate': 0.14808807798324863}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:03,530] Trial 6 finished with value: 0.9071699905033238 and parameters: {'n_estimators': 271, 'max_depth': 9, 'learning_rate': 0.12538906443469508}. Best is trial 0 with value: 0.9231263849319404.
[I 2026-04-03 20:25:03,898] Trial 7 finished with value: 0.9258138123878865 and parameters: {'n_estimators': 262, 'max_depth': 3, 'learning_rate': 0.11412724354946242}. Best is trial 7 with value: 0.9258138123878865.
[I 2026-04-03 20:25:04,024] Trial 8 finished with value: 0.926440329218107 and parameters: {'n_estimators': 83, 'max_depth': 3, 'learning_rate': 0.22690287985805233}. Best is trial 8 with value: 0.926440329218107.
[I 2026-04-03 20:25:04,797] Trial 9 finished with value: 0.9064379550490662 and parameters: {'n_estimators': 232, 'max_depth': 8, 'learning_rate': 0.12522481478160732}. Best is trial 8 with value: 0.926440329218107.
[I 2026-04-03 20:25:05,120] Trial 10 finished with value: 0.9069457634272449 and parameters: {'n_estimators': 70, 'max_depth': 10, 'learning_rate': 0.2179790995872148}. Best is trial 8 with value: 0.926440329218107.
[I 2026-04-03 20:25:05,395] Trial 11 finished with value: 0.9284023161337976 and parameters: {'n_estimators': 188, 'max_depth': 3, 'learning_rate': 0.03275624466738787}. Best is trial 11 with value: 0.9284023161337976.
[I 2026-04-03 20:25:05,654] Trial 12 finished with value: 0.9291607312440646 and parameters: {'n_estimators': 189, 'max_depth': 3, 'learning_rate': 0.04297081575940751}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:05,918] Trial 13 finished with value: 0.9251543209876543 and parameters: {'n_estimators': 177, 'max_depth': 3, 'learning_rate': 0.014431440418175873}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:06,242] Trial 14 finished with value: 0.9219491927825261 and parameters: {'n_estimators': 182, 'max_depth': 4, 'learning_rate': 0.06439913773213068}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:06,999] Trial 15 finished with value: 0.9052838450986599 and parameters: {'n_estimators': 209, 'max_depth': 8, 'learning_rate': 0.015234445980581171}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:07,359] Trial 16 finished with value: 0.9154136330062257 and parameters: {'n_estimators': 161, 'max_depth': 5, 'learning_rate': 0.0836709568280032}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:07,776] Trial 17 finished with value: 0.9142463332278148 and parameters: {'n_estimators': 204, 'max_depth': 5, 'learning_rate': 0.05155450528315683}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:08,246] Trial 18 finished with value: 0.9089242376279413 and parameters: {'n_estimators': 156, 'max_depth': 7, 'learning_rate': 0.09224266003813619}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:08,597] Trial 19 finished with value: 0.928699087263902 and parameters: {'n_estimators': 238, 'max_depth': 3, 'learning_rate': 0.0343348821489005}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:09,037] Trial 20 finished with value: 0.9116215574548907 and parameters: {'n_estimators': 242, 'max_depth': 4, 'learning_rate': 0.17630923826228598}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:09,333] Trial 21 finished with value: 0.929104674475045 and parameters: {'n_estimators': 199, 'max_depth': 3, 'learning_rate': 0.04108335954819489}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:09,762] Trial 22 finished with value: 0.9280626780626781 and parameters: {'n_estimators': 299, 'max_depth': 3, 'learning_rate': 0.03796316999349767}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:10,158] Trial 23 finished with value: 0.9188363933734304 and parameters: {'n_estimators': 216, 'max_depth': 4, 'learning_rate': 0.08006294628546948}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:10,714] Trial 24 finished with value: 0.9179229977841088 and parameters: {'n_estimators': 251, 'max_depth': 5, 'learning_rate': 0.01081885772386771}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:11,006] Trial 25 finished with value: 0.927732932362562 and parameters: {'n_estimators': 197, 'max_depth': 3, 'learning_rate': 0.09708064443986401}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:11,307] Trial 26 finished with value: 0.9239210720692203 and parameters: {'n_estimators': 165, 'max_depth': 4, 'learning_rate': 0.039887738969274875}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:11,627] Trial 27 finished with value: 0.9264963859871268 and parameters: {'n_estimators': 223, 'max_depth': 3, 'learning_rate': 0.06938141319608282}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:11,964] Trial 28 finished with value: 0.9174448665189405 and parameters: {'n_estimators': 147, 'max_depth': 5, 'learning_rate': 0.036186675802997656}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:12,407] Trial 29 finished with value: 0.9206368048960641 and parameters: {'n_estimators': 246, 'max_depth': 4, 'learning_rate': 0.054199470582225684}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:12,756] Trial 30 finished with value: 0.910335549224438 and parameters: {'n_estimators': 111, 'max_depth': 7, 'learning_rate': 0.10961682027072475}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:13,046] Trial 31 finished with value: 0.9283462593647779 and parameters: {'n_estimators': 193, 'max_depth': 3, 'learning_rate': 0.03230568137554102}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:13,318] Trial 32 finished with value: 0.9277659069325737 and parameters: {'n_estimators': 182, 'max_depth': 3, 'learning_rate': 0.06294905755571624}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:13,571] Trial 33 finished with value: 0.9244552601034082 and parameters: {'n_estimators': 130, 'max_depth': 4, 'learning_rate': 0.028315091800495257}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:13,927] Trial 34 finished with value: 0.9210984488762267 and parameters: {'n_estimators': 194, 'max_depth': 4, 'learning_rate': 0.0542874389796087}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:14,241] Trial 35 finished with value: 0.927752717104569 and parameters: {'n_estimators': 209, 'max_depth': 3, 'learning_rate': 0.07614929340591443}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:14,546] Trial 36 finished with value: 0.9247619236045161 and parameters: {'n_estimators': 171, 'max_depth': 4, 'learning_rate': 0.023414049201766707}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:14,888] Trial 37 finished with value: 0.9284946449298301 and parameters: {'n_estimators': 229, 'max_depth': 3, 'learning_rate': 0.05080345809031766}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:15,500] Trial 38 finished with value: 0.9092539833280574 and parameters: {'n_estimators': 284, 'max_depth': 5, 'learning_rate': 0.10057271950709198}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:16,094] Trial 39 finished with value: 0.9087066054658648 and parameters: {'n_estimators': 234, 'max_depth': 6, 'learning_rate': 0.1385052277466431}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:16,473] Trial 40 finished with value: 0.9198717948717948 and parameters: {'n_estimators': 258, 'max_depth': 3, 'learning_rate': 0.18247573895239305}. Best is trial 12 with value: 0.9291607312440646.
[I 2026-04-03 20:25:16,806] Trial 41 finished with value: 0.9296388625092329 and parameters: {'n_estimators': 222, 'max_depth': 3, 'learning_rate': 0.04687983705824872}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:17,141] Trial 42 finished with value: 0.9294278252611586 and parameters: {'n_estimators': 223, 'max_depth': 3, 'learning_rate': 0.04423681492225563}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:17,464] Trial 43 finished with value: 0.9296355650522318 and parameters: {'n_estimators': 217, 'max_depth': 3, 'learning_rate': 0.044995814641020634}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:17,866] Trial 44 finished with value: 0.9218074021314762 and parameters: {'n_estimators': 219, 'max_depth': 4, 'learning_rate': 0.04765805273693887}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:18,734] Trial 45 finished with value: 0.9097486018782315 and parameters: {'n_estimators': 206, 'max_depth': 10, 'learning_rate': 0.07011467948278843}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:19,122] Trial 46 finished with value: 0.9134483486335337 and parameters: {'n_estimators': 261, 'max_depth': 3, 'learning_rate': 0.2789663412419283}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:19,523] Trial 47 finished with value: 0.92457396855545 and parameters: {'n_estimators': 218, 'max_depth': 4, 'learning_rate': 0.02110414568295733}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:20,572] Trial 48 finished with value: 0.9106521050965496 and parameters: {'n_estimators': 274, 'max_depth': 9, 'learning_rate': 0.08842732105808815}. Best is trial 41 with value: 0.9296388625092329.
[I 2026-04-03 20:25:20,872] Trial 49 finished with value: 0.9286232457528754 and parameters: {'n_estimators': 198, 'max_depth': 3, 'learning_rate': 0.06405267520228061}. Best is trial 41 with value: 0.9296388625092329.

Best Parameters: {'n_estimators': 222, 'max_depth': 3, 'learning_rate': 0.04687983705824872}

In [50]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_dia,y_train_dia):
    param2_dia={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'use_label_encoder': False,
        'eval_metric': 'logloss'
    }

    model2_dia=XGBClassifier(**param2_dia)
    model2_dia.fit(X_train_dia,y_train_dia)

    preds=model2_dia.predict_proba(X_test_dia)[:,1]
    return roc_auc_score(y_test_dia,preds)

study2_dia=optuna.create_study(direction='maximize')
study2_dia.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)
model2_dia=study2_dia.best_params
print(f"Best Parameters: {study2_dia.best_params}")

[I 2026-04-03 19:54:01,945] A new study created in memory with name: no-name-9da0e9a9-452c-49b1-b349-a0f03185361f
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,051] Trial 0 finished with value: 0.9110214202806796 and parameters: {'n_estimators': 196, 'max_depth': 5, 'learning_rate': 0.2280788657447983}. Best is trial 0 with value: 0.9110214202806796.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,120] Trial 1 finished with value: 0.9097354120502269 and parameters: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.1570453714112457}. Best is trial 0 with value: 0.9110214202806796.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,193] Trial 2 finished with value: 0.9139165875276987 and parameters: {'n_estimators': 131, 'max_depth': 6, 'learning_rate': 0.1952272723328748}. Best is trial 2 with value: 0.9139165875276987.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,342] Trial 3 finished with value: 0.9112522422707606 and parameters: {'n_estimators': 217, 'max_depth': 8, 'learning_rate': 0.14012255034704066}. Best is trial 2 with value: 0.9139165875276987.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,396] Trial 4 finished with value: 0.922766962118814 and parameters: {'n_estimators': 183, 'max_depth': 3, 'learning_rate': 0.14844795598253754}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,513] Trial 5 finished with value: 0.9040110266962119 and parameters: {'n_estimators': 230, 'max_depth': 7, 'learning_rate': 0.21470306293801703}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,619] Trial 6 finished with value: 0.9093792866941015 and parameters: {'n_estimators': 177, 'max_depth': 7, 'learning_rate': 0.11522135689291085}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,686] Trial 7 finished with value: 0.9151366466181282 and parameters: {'n_estimators': 215, 'max_depth': 3, 'learning_rate': 0.2939853258269131}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,741] Trial 8 finished with value: 0.9111467236467237 and parameters: {'n_estimators': 144, 'max_depth': 4, 'learning_rate': 0.23324111471514897}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:02,814] Trial 9 finished with value: 0.8992692835285427 and parameters: {'n_estimators': 120, 'max_depth': 7, 'learning_rate': 0.26439161317693793}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,040] Trial 10 finished with value: 0.9079811649256093 and parameters: {'n_estimators': 292, 'max_depth': 9, 'learning_rate': 0.04068669010352639}. Best is trial 4 with value: 0.922766962118814.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,119] Trial 11 finished with value: 0.9259325208399282 and parameters: {'n_estimators': 279, 'max_depth': 3, 'learning_rate': 0.07559325711933501}. Best is trial 11 with value: 0.9259325208399282.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,147] Trial 12 finished with value: 0.927485623087475 and parameters: {'n_estimators': 50, 'max_depth': 3, 'learning_rate': 0.0660348041529038}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,179] Trial 13 finished with value: 0.9259127360979214 and parameters: {'n_estimators': 55, 'max_depth': 3, 'learning_rate': 0.0513861821295799}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,415] Trial 14 finished with value: 0.9081262530336605 and parameters: {'n_estimators': 292, 'max_depth': 10, 'learning_rate': 0.0826694658924473}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,479] Trial 15 finished with value: 0.9219920597235411 and parameters: {'n_estimators': 68, 'max_depth': 4, 'learning_rate': 0.016264880554210437}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,586] Trial 16 finished with value: 0.9147409517779889 and parameters: {'n_estimators': 248, 'max_depth': 5, 'learning_rate': 0.09341475041274905}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,632] Trial 17 finished with value: 0.9237364144771553 and parameters: {'n_estimators': 97, 'max_depth': 4, 'learning_rate': 0.07065881360378226}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,712] Trial 18 finished with value: 0.9239606415532342 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.10828071655824391}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,778] Trial 19 finished with value: 0.911298406668777 and parameters: {'n_estimators': 91, 'max_depth': 6, 'learning_rate': 0.03856957865758477}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,872] Trial 20 finished with value: 0.9243464440223699 and parameters: {'n_estimators': 258, 'max_depth': 4, 'learning_rate': 0.012963006126059773}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,906] Trial 21 finished with value: 0.9256753191938376 and parameters: {'n_estimators': 56, 'max_depth': 3, 'learning_rate': 0.04975419519441121}. Best is trial 12 with value: 0.927485623087475.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,947] Trial 22 finished with value: 0.9277626094755724 and parameters: {'n_estimators': 80, 'max_depth': 3, 'learning_rate': 0.06534652557171995}. Best is trial 22 with value: 0.9277626094755724.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:03,989] Trial 23 finished with value: 0.9199410414688192 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.12090655688819998}. Best is trial 22 with value: 0.9277626094755724.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,050] Trial 24 finished with value: 0.9165479582146249 and parameters: {'n_estimators': 112, 'max_depth': 5, 'learning_rate': 0.06815845542391225}. Best is trial 22 with value: 0.9277626094755724.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,108] Trial 25 finished with value: 0.9228329112588372 and parameters: {'n_estimators': 160, 'max_depth': 3, 'learning_rate': 0.18087027060801072}. Best is trial 22 with value: 0.9277626094755724.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,150] Trial 26 finished with value: 0.9248146829165347 and parameters: {'n_estimators': 84, 'max_depth': 4, 'learning_rate': 0.09183117722511464}. Best is trial 22 with value: 0.9277626094755724.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,194] Trial 27 finished with value: 0.9285408093278464 and parameters: {'n_estimators': 104, 'max_depth': 3, 'learning_rate': 0.07097543470719646}. Best is trial 27 with value: 0.9285408093278464.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,244] Trial 28 finished with value: 0.912775667405297 and parameters: {'n_estimators': 70, 'max_depth': 6, 'learning_rate': 0.030016671109069068}. Best is trial 27 with value: 0.9285408093278464.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,308] Trial 29 finished with value: 0.9118589743589743 and parameters: {'n_estimators': 112, 'max_depth': 5, 'learning_rate': 0.13099151110880267}. Best is trial 27 with value: 0.9285408093278464.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,347] Trial 30 finished with value: 0.9189616967394746 and parameters: {'n_estimators': 51, 'max_depth': 5, 'learning_rate': 0.0592170991942636}. Best is trial 27 with value: 0.9285408093278464.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,391] Trial 31 finished with value: 0.9295630209982062 and parameters: {'n_estimators': 99, 'max_depth': 3, 'learning_rate': 0.07926673430332039}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,434] Trial 32 finished with value: 0.9284616703598185 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.09937189887815287}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,505] Trial 33 finished with value: 0.9227010129787907 and parameters: {'n_estimators': 152, 'max_depth': 4, 'learning_rate': 0.10298534839225931}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,556] Trial 34 finished with value: 0.9224701909887095 and parameters: {'n_estimators': 101, 'max_depth': 4, 'learning_rate': 0.16738248327547794}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,603] Trial 35 finished with value: 0.9283792339347895 and parameters: {'n_estimators': 128, 'max_depth': 3, 'learning_rate': 0.09078267621112732}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,654] Trial 36 finished with value: 0.9265854173261581 and parameters: {'n_estimators': 130, 'max_depth': 3, 'learning_rate': 0.1356085601364587}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,737] Trial 37 finished with value: 0.9138374485596708 and parameters: {'n_estimators': 162, 'max_depth': 5, 'learning_rate': 0.1580544538285686}. Best is trial 31 with value: 0.9295630209982062.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [19:54:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 19:54:04,880] Trial 38 finished with value: 0.9068732193732194 and parameters: {'n_estimators': 130, 'max_depth': 8, 'learning_rate': 0.09427887365108299}. Best is trial 31 with value: 0.9295630209982062.

Best Parameters: {'n_estimators': 99, 'max_depth': 3, 'learning_rate': 0.07926673430332039}

In [52]:
from sklearn.model_selection import cross_val_score

def evaluate_params(params, X, y):
    model = XGBClassifier(**params, eval_metric='logloss')
    # We use 'roc_auc' as the scoring metric because of the 9:1 imbalance
    scores = cross_val_score(model, X, y, cv=5, scoring='roc_auc')
    return scores.mean(), scores.std()

mean_a, std_a = evaluate_params(model1_dia, X_train_dia, y_train_dia)
mean_b, std_b = evaluate_params(model2_dia, X_train_dia, y_train_dia)

print(f"Model A: AUC = {mean_a:.4f} (+/- {std_a:.4f})")
print(f"Model B: AUC = {mean_b:.4f} (+/- {std_b:.4f})")

Model A: AUC = 0.9138 (+/- 0.0081)
Model B: AUC = 0.9135 (+/- 0.0082)

heart model

In [62]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_dia,y_train_dia):
    param1_hrt={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'use_label_encoder': False,
        'eval_metric': 'logloss'
    }

    model1_hrt=XGBClassifier(**param1_hrt)
    model1_hrt.fit(X_train_hrt,y_train_hrt)

    preds=model1_hrt.predict_proba(X_test_hrt)[:,1]
    return roc_auc_score(y_test_hrt,preds)

study1_hrt=optuna.create_study(direction='maximize')
study1_hrt.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)

print(f"Best Parameters: {study1_hrt.best_params}")

[I 2026-04-03 22:28:39,914] A new study created in memory with name: no-name-f4f46737-1c8f-4522-a076-c8db5f56c67e
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:40,327] Trial 0 finished with value: 0.8139855072463769 and parameters: {'n_estimators': 291, 'max_depth': 3, 'learning_rate': 0.21167291319238873}. Best is trial 0 with value: 0.8139855072463769.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:40,935] Trial 1 finished with value: 0.8115700483091788 and parameters: {'n_estimators': 213, 'max_depth': 7, 'learning_rate': 0.2807329105610324}. Best is trial 0 with value: 0.8139855072463769.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:41,935] Trial 2 finished with value: 0.8057004830917874 and parameters: {'n_estimators': 290, 'max_depth': 9, 'learning_rate': 0.1797952481365664}. Best is trial 0 with value: 0.8139855072463769.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:41] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:42,035] Trial 3 finished with value: 0.8297222222222222 and parameters: {'n_estimators': 62, 'max_depth': 3, 'learning_rate': 0.01528453289920133}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:42,533] Trial 4 finished with value: 0.82268115942029 and parameters: {'n_estimators': 289, 'max_depth': 4, 'learning_rate': 0.0407112509680445}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:42] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:43,010] Trial 5 finished with value: 0.813743961352657 and parameters: {'n_estimators': 226, 'max_depth': 5, 'learning_rate': 0.14101107651294226}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:43,456] Trial 6 finished with value: 0.8160386473429952 and parameters: {'n_estimators': 178, 'max_depth': 6, 'learning_rate': 0.20924424568560893}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:43] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:44,338] Trial 7 finished with value: 0.8058454106280194 and parameters: {'n_estimators': 243, 'max_depth': 9, 'learning_rate': 0.1118515761928899}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:44,754] Trial 8 finished with value: 0.8188647342995169 and parameters: {'n_estimators': 126, 'max_depth': 9, 'learning_rate': 0.1959460711666848}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:44,946] Trial 9 finished with value: 0.813671497584541 and parameters: {'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.22566450871787405}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:45,045] Trial 10 finished with value: 0.8244565217391304 and parameters: {'n_estimators': 53, 'max_depth': 3, 'learning_rate': 0.013566549258194671}. Best is trial 3 with value: 0.8297222222222222.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:45,138] Trial 11 finished with value: 0.8336352657004831 and parameters: {'n_estimators': 50, 'max_depth': 3, 'learning_rate': 0.01924256173370346}. Best is trial 11 with value: 0.8336352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:45,333] Trial 12 finished with value: 0.8323792270531402 and parameters: {'n_estimators': 102, 'max_depth': 4, 'learning_rate': 0.0715594968476771}. Best is trial 11 with value: 0.8336352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:45,566] Trial 13 finished with value: 0.8377053140096618 and parameters: {'n_estimators': 104, 'max_depth': 5, 'learning_rate': 0.07446870329696734}. Best is trial 13 with value: 0.8377053140096618.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:45,891] Trial 14 finished with value: 0.8409661835748793 and parameters: {'n_estimators': 108, 'max_depth': 7, 'learning_rate': 0.087468228325516}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:46,262] Trial 15 finished with value: 0.8268840579710145 and parameters: {'n_estimators': 122, 'max_depth': 7, 'learning_rate': 0.08910443892593621}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:46,661] Trial 16 finished with value: 0.8115700483091788 and parameters: {'n_estimators': 156, 'max_depth': 6, 'learning_rate': 0.12761508975169675}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:46,992] Trial 17 finished with value: 0.8256521739130434 and parameters: {'n_estimators': 97, 'max_depth': 8, 'learning_rate': 0.066919674095687}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:47,342] Trial 18 finished with value: 0.8229710144927537 and parameters: {'n_estimators': 162, 'max_depth': 5, 'learning_rate': 0.10159264238613129}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:47,718] Trial 19 finished with value: 0.817487922705314 and parameters: {'n_estimators': 86, 'max_depth': 10, 'learning_rate': 0.16188498826124598}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:48,040] Trial 20 finished with value: 0.8363526570048309 and parameters: {'n_estimators': 144, 'max_depth': 5, 'learning_rate': 0.057864280126339485}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:48,351] Trial 21 finished with value: 0.8379468599033817 and parameters: {'n_estimators': 138, 'max_depth': 5, 'learning_rate': 0.05296458733372107}. Best is trial 14 with value: 0.8409661835748793.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:48,680] Trial 22 finished with value: 0.8472705314009662 and parameters: {'n_estimators': 124, 'max_depth': 6, 'learning_rate': 0.046552920313087505}. Best is trial 22 with value: 0.8472705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:49,244] Trial 23 finished with value: 0.8403140096618358 and parameters: {'n_estimators': 190, 'max_depth': 7, 'learning_rate': 0.03736097651630486}. Best is trial 22 with value: 0.8472705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:49,813] Trial 24 finished with value: 0.8350966183574879 and parameters: {'n_estimators': 196, 'max_depth': 7, 'learning_rate': 0.03990250504978883}. Best is trial 22 with value: 0.8472705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:50,418] Trial 25 finished with value: 0.8144927536231885 and parameters: {'n_estimators': 182, 'max_depth': 8, 'learning_rate': 0.09467336577308011}. Best is trial 22 with value: 0.8472705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:50,645] Trial 26 finished with value: 0.8535869565217392 and parameters: {'n_estimators': 80, 'max_depth': 6, 'learning_rate': 0.036670674836914705}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:50,854] Trial 27 finished with value: 0.8432367149758454 and parameters: {'n_estimators': 74, 'max_depth': 6, 'learning_rate': 0.11427095129506046}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:51,067] Trial 28 finished with value: 0.840072463768116 and parameters: {'n_estimators': 76, 'max_depth': 6, 'learning_rate': 0.12072072117120933}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:51,282] Trial 29 finished with value: 0.8332850241545894 and parameters: {'n_estimators': 77, 'max_depth': 6, 'learning_rate': 0.2385978660059261}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:51,514] Trial 30 finished with value: 0.8248067632850242 and parameters: {'n_estimators': 121, 'max_depth': 4, 'learning_rate': 0.1526730254286219}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:51,902] Trial 31 finished with value: 0.8321256038647342 and parameters: {'n_estimators': 110, 'max_depth': 8, 'learning_rate': 0.08667334464988613}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:52,141] Trial 32 finished with value: 0.8525845410628019 and parameters: {'n_estimators': 87, 'max_depth': 6, 'learning_rate': 0.03766669006314276}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:52,352] Trial 33 finished with value: 0.8471618357487922 and parameters: {'n_estimators': 73, 'max_depth': 6, 'learning_rate': 0.03295922935154512}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:52,567] Trial 34 finished with value: 0.8522342995169083 and parameters: {'n_estimators': 89, 'max_depth': 6, 'learning_rate': 0.029848281602554937}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:52,862] Trial 35 finished with value: 0.8308212560386474 and parameters: {'n_estimators': 91, 'max_depth': 7, 'learning_rate': 0.02414937725842324}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:53,175] Trial 36 finished with value: 0.8430434782608696 and parameters: {'n_estimators': 136, 'max_depth': 5, 'learning_rate': 0.010355299119811184}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:53,365] Trial 37 finished with value: 0.8407971014492754 and parameters: {'n_estimators': 66, 'max_depth': 6, 'learning_rate': 0.29314247375628444}. Best is trial 26 with value: 0.8535869565217392.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:28:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:28:53,536] Trial 38 finished with value: 0.8379106280193237 and parameters: {'n_estimators': 86, 'max_depth': 4, 'learning_rate': 0.056733158636530445}. Best is trial 26 with value: 0.8535869565217392.

Best Parameters: {'n_estimators': 80, 'max_depth': 6, 'learning_rate': 0.036670674836914705}

In [55]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_dia,y_train_dia):
    param2_hrt={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'use_label_encoder': False,
        'eval_metric': 'logloss'
    }

    model2_hrt=XGBClassifier(**param2_hrt)
    model2_hrt.fit(X_train_hrt,y_train_hrt)

    preds=model2_hrt.predict_proba(X_test_hrt)[:,1]
    return roc_auc_score(y_test_hrt,preds)

study2_hrt=optuna.create_study(direction='maximize')
study2_hrt.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)
model2_hrt=study1_hrt.best_params
print(f"Best Parameters: {study2_hrt.best_params}")

[I 2026-04-03 20:07:57,388] A new study created in memory with name: no-name-dab71db5-6281-42e4-ab52-33c9085bc3f5
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:57,954] Trial 0 finished with value: 0.8522705314009662 and parameters: {'n_estimators': 223, 'max_depth': 6, 'learning_rate': 0.022666693436106063}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:58,157] Trial 1 finished with value: 0.8185265700483091 and parameters: {'n_estimators': 138, 'max_depth': 3, 'learning_rate': 0.1693801916420624}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:58,351] Trial 2 finished with value: 0.80756038647343 and parameters: {'n_estimators': 102, 'max_depth': 4, 'learning_rate': 0.20436865557554576}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:58,928] Trial 3 finished with value: 0.8298550724637681 and parameters: {'n_estimators': 204, 'max_depth': 7, 'learning_rate': 0.059061550653293785}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:59,244] Trial 4 finished with value: 0.8026811594202898 and parameters: {'n_estimators': 229, 'max_depth': 3, 'learning_rate': 0.276868634834384}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:59,414] Trial 5 finished with value: 0.8170048309178745 and parameters: {'n_estimators': 118, 'max_depth': 3, 'learning_rate': 0.216973855192059}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:07:59,762] Trial 6 finished with value: 0.8197342995169081 and parameters: {'n_estimators': 170, 'max_depth': 5, 'learning_rate': 0.11988434050541433}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:07:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:00,470] Trial 7 finished with value: 0.8078985507246377 and parameters: {'n_estimators': 173, 'max_depth': 10, 'learning_rate': 0.019302713465785312}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:00,696] Trial 8 finished with value: 0.8328743961352657 and parameters: {'n_estimators': 63, 'max_depth': 9, 'learning_rate': 0.26832613783526094}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:01,275] Trial 9 finished with value: 0.7997342995169082 and parameters: {'n_estimators': 215, 'max_depth': 7, 'learning_rate': 0.2739490871407166}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:02,010] Trial 10 finished with value: 0.8190821256038647 and parameters: {'n_estimators': 296, 'max_depth': 6, 'learning_rate': 0.10740792894860585}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:02,265] Trial 11 finished with value: 0.8189855072463769 and parameters: {'n_estimators': 68, 'max_depth': 9, 'learning_rate': 0.06522580745638835}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:02] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:03,098] Trial 12 finished with value: 0.7831159420289855 and parameters: {'n_estimators': 267, 'max_depth': 8, 'learning_rate': 0.2985532613161605}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:03,349] Trial 13 finished with value: 0.820024154589372 and parameters: {'n_estimators': 57, 'max_depth': 10, 'learning_rate': 0.23530154902063768}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:03] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:04,180] Trial 14 finished with value: 0.8059661835748793 and parameters: {'n_estimators': 255, 'max_depth': 8, 'learning_rate': 0.15489448863551974}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:04,598] Trial 15 finished with value: 0.8441304347826086 and parameters: {'n_estimators': 157, 'max_depth': 6, 'learning_rate': 0.011801165357979027}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:04] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:05,020] Trial 16 finished with value: 0.8453019323671498 and parameters: {'n_estimators': 192, 'max_depth': 5, 'learning_rate': 0.02059156118106223}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:05,450] Trial 17 finished with value: 0.8297826086956521 and parameters: {'n_estimators': 198, 'max_depth': 5, 'learning_rate': 0.05590832096199887}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:05,978] Trial 18 finished with value: 0.8240579710144929 and parameters: {'n_estimators': 244, 'max_depth': 5, 'learning_rate': 0.08734241585231275}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:05] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:06,486] Trial 19 finished with value: 0.8244444444444444 and parameters: {'n_estimators': 285, 'max_depth': 4, 'learning_rate': 0.036103561078671756}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:06,970] Trial 20 finished with value: 0.8248067632850241 and parameters: {'n_estimators': 188, 'max_depth': 6, 'learning_rate': 0.1344438592903767}. Best is trial 0 with value: 0.8522705314009662.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:07,409] Trial 21 finished with value: 0.8528260869565217 and parameters: {'n_estimators': 166, 'max_depth': 6, 'learning_rate': 0.01857817262237078}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:07,720] Trial 22 finished with value: 0.8412077294685991 and parameters: {'n_estimators': 148, 'max_depth': 5, 'learning_rate': 0.03351291436222443}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:07] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:08,393] Trial 23 finished with value: 0.8205072463768116 and parameters: {'n_estimators': 227, 'max_depth': 7, 'learning_rate': 0.08400628528099155}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:08,739] Trial 24 finished with value: 0.8344806763285024 and parameters: {'n_estimators': 188, 'max_depth': 4, 'learning_rate': 0.04067188293988422}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:09,073] Trial 25 finished with value: 0.8444685990338165 and parameters: {'n_estimators': 122, 'max_depth': 6, 'learning_rate': 0.014182825413234042}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:09,561] Trial 26 finished with value: 0.8281884057971014 and parameters: {'n_estimators': 224, 'max_depth': 5, 'learning_rate': 0.08838626567121377}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:09] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:10,058] Trial 27 finished with value: 0.8240821256038647 and parameters: {'n_estimators': 162, 'max_depth': 7, 'learning_rate': 0.048879028733423716}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:10,875] Trial 28 finished with value: 0.8278743961352657 and parameters: {'n_estimators': 244, 'max_depth': 8, 'learning_rate': 0.07138504875989528}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:11,131] Trial 29 finished with value: 0.8302173913043478 and parameters: {'n_estimators': 135, 'max_depth': 4, 'learning_rate': 0.17475813877277785}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:11,383] Trial 30 finished with value: 0.851304347826087 and parameters: {'n_estimators': 88, 'max_depth': 6, 'learning_rate': 0.030322628335978926}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:11,633] Trial 31 finished with value: 0.8486352657004831 and parameters: {'n_estimators': 88, 'max_depth': 6, 'learning_rate': 0.026784761184015807}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:11,885] Trial 32 finished with value: 0.8525603864734299 and parameters: {'n_estimators': 91, 'max_depth': 6, 'learning_rate': 0.034736706446044305}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:11] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:12,137] Trial 33 finished with value: 0.8352294685990338 and parameters: {'n_estimators': 78, 'max_depth': 7, 'learning_rate': 0.046566550718925515}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:12,428] Trial 34 finished with value: 0.8453381642512077 and parameters: {'n_estimators': 106, 'max_depth': 6, 'learning_rate': 0.06427262651586077}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:12,743] Trial 35 finished with value: 0.8256400966183575 and parameters: {'n_estimators': 98, 'max_depth': 7, 'learning_rate': 0.010205376798892076}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:12,899] Trial 36 finished with value: 0.8499758454106279 and parameters: {'n_estimators': 50, 'max_depth': 6, 'learning_rate': 0.09954441943942535}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:12] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:13,193] Trial 37 finished with value: 0.8459057971014492 and parameters: {'n_estimators': 127, 'max_depth': 5, 'learning_rate': 0.03754446090804322}. Best is trial 21 with value: 0.8528260869565217.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:08:13] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 20:08:13,570] Trial 38 finished with value: 0.8242995169082126 and parameters: {'n_estimators': 106, 'max_depth': 8, 'learning_rate': 0.07326197032374211}. Best is trial 21 with value: 0.8528260869565217.

Best Parameters: {'n_estimators': 166, 'max_depth': 6, 'learning_rate': 0.01857817262237078}

In [56]:
from sklearn.model_selection import cross_val_score

def evaluate_params(params, X, y):
    model = XGBClassifier(**params, eval_metric='logloss')
    # We use 'roc_auc' as the scoring metric because of the 9:1 imbalance
    scores = cross_val_score(model, X, y, cv=5, scoring='roc_auc')
    return scores.mean(), scores.std()

mean_a, std_a = evaluate_params(model1_hrt, X_train_hrt, y_train_hrt)
mean_b, std_b = evaluate_params(model2_hrt, X_train_hrt, y_train_hrt)

print(f"Model A: AUC = {mean_a:.4f} (+/- {std_a:.4f})")
print(f"Model B: AUC = {mean_b:.4f} (+/- {std_b:.4f})")

Model A: AUC = 0.7777 (+/- 0.0247)
Model B: AUC = 0.7777 (+/- 0.0247)

Liver model

In [63]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_lvr,y_train_lvr):
    param1_lvr={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'use_label_encoder': False,
        'eval_metric': 'logloss'
    }

    model1_lvr=XGBClassifier(**param1_lvr)
    model1_lvr.fit(X_train_lvr,y_train_lvr)

    preds=model1_lvr.predict_proba(X_test_hrt)[:,1]
    return roc_auc_score(y_test_hrt,preds)

study1_lvr=optuna.create_study(direction='maximize')
study1_lvr.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)

print(f"Best Parameters: {study1_lvr.best_params}")

[I 2026-04-03 22:29:14,561] A new study created in memory with name: no-name-c377ef1d-1d41-490a-ad23-85e1fc6da8b9
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:14,773] Trial 0 finished with value: 0.806304347826087 and parameters: {'n_estimators': 93, 'max_depth': 5, 'learning_rate': 0.27566864579417716}. Best is trial 0 with value: 0.806304347826087.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:14] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:15,087] Trial 1 finished with value: 0.8085748792270531 and parameters: {'n_estimators': 224, 'max_depth': 3, 'learning_rate': 0.11708637371565069}. Best is trial 1 with value: 0.8085748792270531.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:15,653] Trial 2 finished with value: 0.7959420289855073 and parameters: {'n_estimators': 192, 'max_depth': 7, 'learning_rate': 0.2094256142847773}. Best is trial 1 with value: 0.8085748792270531.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:15] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:16,089] Trial 3 finished with value: 0.8011835748792271 and parameters: {'n_estimators': 129, 'max_depth': 8, 'learning_rate': 0.24374396044819088}. Best is trial 1 with value: 0.8085748792270531.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:16,455] Trial 4 finished with value: 0.8155797101449275 and parameters: {'n_estimators': 206, 'max_depth': 4, 'learning_rate': 0.2013213378393341}. Best is trial 4 with value: 0.8155797101449275.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:16,941] Trial 5 finished with value: 0.8059903381642513 and parameters: {'n_estimators': 130, 'max_depth': 9, 'learning_rate': 0.2632218222952825}. Best is trial 4 with value: 0.8155797101449275.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:17,575] Trial 6 finished with value: 0.8065700483091788 and parameters: {'n_estimators': 189, 'max_depth': 8, 'learning_rate': 0.21331889320248024}. Best is trial 4 with value: 0.8155797101449275.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:17] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:18,607] Trial 7 finished with value: 0.7920289855072463 and parameters: {'n_estimators': 280, 'max_depth': 9, 'learning_rate': 0.17705319279887768}. Best is trial 4 with value: 0.8155797101449275.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:18,853] Trial 8 finished with value: 0.8140338164251208 and parameters: {'n_estimators': 152, 'max_depth': 4, 'learning_rate': 0.24535147972562218}. Best is trial 4 with value: 0.8155797101449275.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:18] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:19,831] Trial 9 finished with value: 0.8181884057971014 and parameters: {'n_estimators': 295, 'max_depth': 8, 'learning_rate': 0.06392907193251383}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:21,198] Trial 10 finished with value: 0.8109782608695651 and parameters: {'n_estimators': 298, 'max_depth': 10, 'learning_rate': 0.01210173365719025}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:21,811] Trial 11 finished with value: 0.8079227053140096 and parameters: {'n_estimators': 244, 'max_depth': 6, 'learning_rate': 0.09934916927092106}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:21,984] Trial 12 finished with value: 0.8146618357487923 and parameters: {'n_estimators': 57, 'max_depth': 6, 'learning_rate': 0.0342811756644498}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:21] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:22,347] Trial 13 finished with value: 0.8121014492753623 and parameters: {'n_estimators': 252, 'max_depth': 3, 'learning_rate': 0.07861482064277671}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:22] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:22,819] Trial 14 finished with value: 0.8093719806763285 and parameters: {'n_estimators': 219, 'max_depth': 5, 'learning_rate': 0.1516156434420024}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:22] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:23,596] Trial 15 finished with value: 0.8180434782608695 and parameters: {'n_estimators': 268, 'max_depth': 7, 'learning_rate': 0.054091855856500434}. Best is trial 9 with value: 0.8181884057971014.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:23] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:24,418] Trial 16 finished with value: 0.8203623188405796 and parameters: {'n_estimators': 272, 'max_depth': 7, 'learning_rate': 0.0547703371927204}. Best is trial 16 with value: 0.8203623188405796.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:24] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:25,396] Trial 17 finished with value: 0.8047826086956521 and parameters: {'n_estimators': 290, 'max_depth': 8, 'learning_rate': 0.13354030892304297}. Best is trial 16 with value: 0.8203623188405796.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:25] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:26,447] Trial 18 finished with value: 0.8012801932367151 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.06918238036113185}. Best is trial 16 with value: 0.8203623188405796.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:26] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:27,227] Trial 19 finished with value: 0.8229710144927537 and parameters: {'n_estimators': 269, 'max_depth': 7, 'learning_rate': 0.031380031661028394}. Best is trial 19 with value: 0.8229710144927537.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:27] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:27,924] Trial 20 finished with value: 0.813743961352657 and parameters: {'n_estimators': 232, 'max_depth': 7, 'learning_rate': 0.012080091150417457}. Best is trial 19 with value: 0.8229710144927537.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:27] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:28,818] Trial 21 finished with value: 0.8258454106280193 and parameters: {'n_estimators': 266, 'max_depth': 8, 'learning_rate': 0.04488499168981068}. Best is trial 21 with value: 0.8258454106280193.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:28] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:29,419] Trial 22 finished with value: 0.8242753623188406 and parameters: {'n_estimators': 268, 'max_depth': 6, 'learning_rate': 0.03699321985246411}. Best is trial 21 with value: 0.8258454106280193.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:29] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:30,076] Trial 23 finished with value: 0.81256038647343 and parameters: {'n_estimators': 261, 'max_depth': 6, 'learning_rate': 0.09703631276135646}. Best is trial 21 with value: 0.8258454106280193.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:30] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:30,437] Trial 24 finished with value: 0.8099516908212561 and parameters: {'n_estimators': 173, 'max_depth': 5, 'learning_rate': 0.03916754016694202}. Best is trial 21 with value: 0.8258454106280193.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:30] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:31,357] Trial 25 finished with value: 0.8281159420289854 and parameters: {'n_estimators': 229, 'max_depth': 9, 'learning_rate': 0.03926013771320521}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:31] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:32,267] Trial 26 finished with value: 0.8091304347826087 and parameters: {'n_estimators': 236, 'max_depth': 9, 'learning_rate': 0.09600884221620082}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:33,111] Trial 27 finished with value: 0.81 and parameters: {'n_estimators': 213, 'max_depth': 9, 'learning_rate': 0.08451513500341865}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:33,939] Trial 28 finished with value: 0.8066425120772946 and parameters: {'n_estimators': 194, 'max_depth': 10, 'learning_rate': 0.12849406337848376}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:34,806] Trial 29 finished with value: 0.8237439613526569 and parameters: {'n_estimators': 245, 'max_depth': 8, 'learning_rate': 0.038951186116974346}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:34] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:35,937] Trial 30 finished with value: 0.8223671497584542 and parameters: {'n_estimators': 283, 'max_depth': 9, 'learning_rate': 0.015726794335060603}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:35] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:36,786] Trial 31 finished with value: 0.827463768115942 and parameters: {'n_estimators': 254, 'max_depth': 8, 'learning_rate': 0.044881305381833866}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:36] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:37,557] Trial 32 finished with value: 0.81731884057971 and parameters: {'n_estimators': 227, 'max_depth': 8, 'learning_rate': 0.056510336443846496}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:37] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:38,200] Trial 33 finished with value: 0.810024154589372 and parameters: {'n_estimators': 253, 'max_depth': 6, 'learning_rate': 0.1105857232778096}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:39,196] Trial 34 finished with value: 0.8185990338164251 and parameters: {'n_estimators': 262, 'max_depth': 9, 'learning_rate': 0.0432916878001949}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:39,880] Trial 35 finished with value: 0.8160144927536231 and parameters: {'n_estimators': 206, 'max_depth': 8, 'learning_rate': 0.07544958095775298}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:40,423] Trial 36 finished with value: 0.8139009661835748 and parameters: {'n_estimators': 170, 'max_depth': 7, 'learning_rate': 0.019231155598985552}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:40] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:41,657] Trial 37 finished with value: 0.817463768115942 and parameters: {'n_estimators': 281, 'max_depth': 10, 'learning_rate': 0.025415264646218953}. Best is trial 25 with value: 0.8281159420289854.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:29:41] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:29:42,478] Trial 38 finished with value: 0.81743961352657 and parameters: {'n_estimators': 237, 'max_depth': 8, 'learning_rate': 0.050851328974406904}. Best is trial 25 with value: 0.8281159420289854.

Best Parameters: {'n_estimators': 229, 'max_depth': 9, 'learning_rate': 0.03926013771320521}

In [64]:
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier
import optuna

def objective(trial,X_train_lvr,y_train_lvr):
    param2_lvr={
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'scale_pos_weight': 9, # Handles your 9:1 imbalance!
        'use_label_encoder': False,
        'eval_metric': 'logloss'
    }

    model2_lvr=XGBClassifier(**param2_lvr)
    model2_lvr.fit(X_train_lvr,y_train_lvr)

    preds=model2_lvr.predict_proba(X_test_hrt)[:,1]
    return roc_auc_score(y_test_hrt,preds)

study2_lvr=optuna.create_study(direction='maximize')
study2_lvr.optimize(lambda trial: objective(trial,X_train_dia,y_train_dia),n_trials=50)

print(f"Best Parameters: {study2_lvr.best_params}")

[I 2026-04-03 22:34:44,689] A new study created in memory with name: no-name-f30f7a57-0a98-4fcf-928a-469222252a3c
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:45,417] Trial 0 finished with value: 0.8040096618357487 and parameters: {'n_estimators': 247, 'max_depth': 7, 'learning_rate': 0.14182745035362265}. Best is trial 0 with value: 0.8040096618357487.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:45,535] Trial 1 finished with value: 0.802572463768116 and parameters: {'n_estimators': 56, 'max_depth': 5, 'learning_rate': 0.013272518215701948}. Best is trial 0 with value: 0.8040096618357487.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:46,224] Trial 2 finished with value: 0.7941545893719807 and parameters: {'n_estimators': 169, 'max_depth': 10, 'learning_rate': 0.17762789187091327}. Best is trial 0 with value: 0.8040096618357487.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:46,483] Trial 3 finished with value: 0.8115458937198068 and parameters: {'n_estimators': 183, 'max_depth': 3, 'learning_rate': 0.16455780893992705}. Best is trial 3 with value: 0.8115458937198068.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:47,101] Trial 4 finished with value: 0.8088164251207729 and parameters: {'n_estimators': 210, 'max_depth': 7, 'learning_rate': 0.130774251370958}. Best is trial 3 with value: 0.8115458937198068.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:47,399] Trial 5 finished with value: 0.8091787439613527 and parameters: {'n_estimators': 167, 'max_depth': 4, 'learning_rate': 0.2651614918269954}. Best is trial 3 with value: 0.8115458937198068.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:47,721] Trial 6 finished with value: 0.8068599033816426 and parameters: {'n_estimators': 149, 'max_depth': 5, 'learning_rate': 0.11106624142449378}. Best is trial 3 with value: 0.8115458937198068.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:47] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:48,256] Trial 7 finished with value: 0.813743961352657 and parameters: {'n_estimators': 158, 'max_depth': 8, 'learning_rate': 0.08701729196419307}. Best is trial 7 with value: 0.813743961352657.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:48,953] Trial 8 finished with value: 0.8091304347826087 and parameters: {'n_estimators': 212, 'max_depth': 8, 'learning_rate': 0.18063506147632194}. Best is trial 7 with value: 0.813743961352657.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:48] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:49,415] Trial 9 finished with value: 0.8218840579710145 and parameters: {'n_estimators': 128, 'max_depth': 8, 'learning_rate': 0.05032547961152816}. Best is trial 9 with value: 0.8218840579710145.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:49,838] Trial 10 finished with value: 0.8003019323671499 and parameters: {'n_estimators': 83, 'max_depth': 10, 'learning_rate': 0.01628538410972674}. Best is trial 9 with value: 0.8218840579710145.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:49] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:50,246] Trial 11 finished with value: 0.8179468599033817 and parameters: {'n_estimators': 113, 'max_depth': 8, 'learning_rate': 0.07424253402113436}. Best is trial 9 with value: 0.8218840579710145.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:50,687] Trial 12 finished with value: 0.825072463768116 and parameters: {'n_estimators': 107, 'max_depth': 9, 'learning_rate': 0.06166357038640786}. Best is trial 12 with value: 0.825072463768116.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:50] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:51,147] Trial 13 finished with value: 0.8253140096618358 and parameters: {'n_estimators': 110, 'max_depth': 9, 'learning_rate': 0.059627962257854716}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:51] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:52,204] Trial 14 finished with value: 0.7923671497584541 and parameters: {'n_estimators': 295, 'max_depth': 9, 'learning_rate': 0.2382952937818169}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:52,604] Trial 15 finished with value: 0.8216666666666667 and parameters: {'n_estimators': 94, 'max_depth': 9, 'learning_rate': 0.054481087209653785}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:52,792] Trial 16 finished with value: 0.8148309178743961 and parameters: {'n_estimators': 66, 'max_depth': 6, 'learning_rate': 0.09609781975705789}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:53,221] Trial 17 finished with value: 0.8046376811594202 and parameters: {'n_estimators': 116, 'max_depth': 9, 'learning_rate': 0.2133482467304609}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:53,824] Trial 18 finished with value: 0.8132125603864735 and parameters: {'n_estimators': 133, 'max_depth': 10, 'learning_rate': 0.045584200447951875}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:53] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:54,080] Trial 19 finished with value: 0.8177777777777777 and parameters: {'n_estimators': 93, 'max_depth': 6, 'learning_rate': 0.11962831993313285}. Best is trial 13 with value: 0.8253140096618358.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:54,431] Trial 20 finished with value: 0.8259661835748794 and parameters: {'n_estimators': 81, 'max_depth': 9, 'learning_rate': 0.06213928293937252}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:54,752] Trial 21 finished with value: 0.821304347826087 and parameters: {'n_estimators': 76, 'max_depth': 9, 'learning_rate': 0.06969992639253357}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:54] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:55,225] Trial 22 finished with value: 0.8102657004830918 and parameters: {'n_estimators': 96, 'max_depth': 10, 'learning_rate': 0.03311064884291039}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:55,466] Trial 23 finished with value: 0.8252415458937197 and parameters: {'n_estimators': 53, 'max_depth': 9, 'learning_rate': 0.09570232374207163}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:55,648] Trial 24 finished with value: 0.8165700483091788 and parameters: {'n_estimators': 51, 'max_depth': 7, 'learning_rate': 0.10320337323826034}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:55,915] Trial 25 finished with value: 0.825024154589372 and parameters: {'n_estimators': 71, 'max_depth': 8, 'learning_rate': 0.0839745389687705}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:56,160] Trial 26 finished with value: 0.817524154589372 and parameters: {'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.03860089192151653}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:56,735] Trial 27 finished with value: 0.8064009661835749 and parameters: {'n_estimators': 132, 'max_depth': 10, 'learning_rate': 0.1457719221004296}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:56] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:56,984] Trial 28 finished with value: 0.811256038647343 and parameters: {'n_estimators': 75, 'max_depth': 7, 'learning_rate': 0.12096346489043838}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:57,876] Trial 29 finished with value: 0.7843236714975845 and parameters: {'n_estimators': 275, 'max_depth': 8, 'learning_rate': 0.2900122621365982}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:58,160] Trial 30 finished with value: 0.8198550724637682 and parameters: {'n_estimators': 102, 'max_depth': 6, 'learning_rate': 0.03182966386198907}. Best is trial 20 with value: 0.8259661835748794.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:58,615] Trial 31 finished with value: 0.8261352657004831 and parameters: {'n_estimators': 112, 'max_depth': 9, 'learning_rate': 0.06772768121704083}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:58,889] Trial 32 finished with value: 0.8240579710144926 and parameters: {'n_estimators': 64, 'max_depth': 9, 'learning_rate': 0.0779407264430496}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:59,334] Trial 33 finished with value: 0.8035748792270531 and parameters: {'n_estimators': 87, 'max_depth': 10, 'learning_rate': 0.019323148192454183}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:34:59,907] Trial 34 finished with value: 0.8224396135265701 and parameters: {'n_estimators': 144, 'max_depth': 9, 'learning_rate': 0.06234770966459549}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:34:59] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:35:00,467] Trial 35 finished with value: 0.8183333333333332 and parameters: {'n_estimators': 185, 'max_depth': 7, 'learning_rate': 0.09639833360913205}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:35:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:35:00,966] Trial 36 finished with value: 0.8015458937198067 and parameters: {'n_estimators': 117, 'max_depth': 10, 'learning_rate': 0.14077903384333243}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:35:00] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:35:01,254] Trial 37 finished with value: 0.7984541062801932 and parameters: {'n_estimators': 195, 'max_depth': 3, 'learning_rate': 0.1827159933428027}. Best is trial 31 with value: 0.8261352657004831.
C:\Users\Dev Patel\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:35:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2026-04-03 22:35:01,479] Trial 38 finished with value: 0.8154589371980677 and parameters: {'n_estimators': 61, 'max_depth': 8, 'learning_rate': 0.11401174998793856}. Best is trial 31 with value: 0.8261352657004831.

Best Parameters: {'n_estimators': 112, 'max_depth': 9, 'learning_rate': 0.06772768121704083}

testing

testing

In [65]:
import pandas as pd

# 1. Define a "Virtual Patient"
# Order: ['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC']
# Gender: 1=Male, 2=Female | Age: 55 | BMI: 32 | Glucose: 150 | Bilirubin: 1.2 | ALT: 45
test_patient = pd.DataFrame([[1, 55, 32.5, 150.0, 1.2, 45.0]], 
                            columns=['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC'])

# 2. Get Probabilities from each Specialist
# We take the [0][1] element: [First patient in list][Probability of Class 1]
prob_diabetes = model1_dia.predict_proba(test_patient)[0][1]
prob_heart    = model1_hrt.predict_proba(test_patient)[0][1]
prob_liver    = model2_lvr.predict_proba(test_patient)[0][1]

# 3. Display the Results
print("--- Patient Risk Profile ---")
print(f"Diabetes Risk: {prob_diabetes:.1%}")
print(f"Heart Disease Risk: {prob_heart:.1%}")
print(f"Liver Disease Risk: {prob_liver:.1%}")

AttributeError: 'dict' object has no attribute 'predict_proba'

In [59]:
import pandas as pd

# 1. Define a "Virtual Patient"
# Order: ['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC']
# Gender: 1=Male, 2=Female | Age: 55 | BMI: 32 | Glucose: 150 | Bilirubin: 1.2 | ALT: 45
test_patient = pd.DataFrame([[1, 55, 32.5, 150.0, 1.2, 45.0]], 
                            columns=['RIAGENDR', 'RIDAGEYR', 'BMXBMI', 'LBXSGL', 'LBXSIR', 'LBDSATLC'])

# 2. Get Probabilities from each Specialist
# We take the [0][1] element: [First patient in list][Probability of Class 1]
prob_diabetes = model1_dia.predict_proba(test_patient)[0][1]
prob_heart    = model1_hrt.predict_proba(test_patient)[0][1]
prob_liver    = model1_lvr.predict_proba(test_patient)[0][1]

# 3. Display the Results
print("--- Patient Risk Profile ---")
print(f"Diabetes Risk: {prob_diabetes:.1%}")
print(f"Heart Disease Risk: {prob_heart:.1%}")
print(f"Liver Disease Risk: {prob_liver:.1%}")

AttributeError: 'dict' object has no attribute 'predict_proba'